//! Short clued words keep every letter target usable on narrow screens.
pub(super) const WORDS: &[(&str, &str)] = &[
    ("BRICK", "A block used to build a wall"),
    ("CABIN", "A small wooden house"),
    ("QUIET", "Making very little noise"),
    ("RUNE", "An ancient carved symbol"),
    ("TAPES", "Old cassettes hold these"),
    ("APPLE", "A fruit that grows in an orchard"),
    ("BREAD", "A loaf from the bakery"),
    ("CLOUD", "A white shape in the sky"),
    ("DREAM", "A story you see while asleep"),
    ("EARTH", "The planet we call home"),
    ("FLAME", "The glowing part of a fire"),
    ("GRAPE", "A small fruit growing in bunches"),
    ("HOUSE", "A building you live in"),
    ("IVORY", "The material of an elephant tusk"),
    ("JELLY", "A wobbly sweet dessert"),
    ("KNIFE", "A tool used for cutting"),
    ("LEMON", "A sour yellow fruit"),
    ("MAPLE", "A tree famous for its syrup"),
    ("NIGHT", "The time between dusk and dawn"),
    ("OCEAN", "A vast expanse of salt water"),
    ("PEARL", "A gem formed inside an oyster"),
    ("QUILT", "A blanket sewn from patches"),
    ("RIVER", "Water flowing toward the sea"),
    ("STONE", "A small piece of rock"),
    ("TIGER", "A big cat with stripes"),
    ("UNCLE", "Your parent's brother"),
    ("VIOLA", "A string instrument larger than a violin"),
    ("WHALE", "A huge mammal of the sea"),
    ("YACHT", "A boat used for sailing"),
    ("ZEBRA", "A striped relative of the horse"),
    ("CLOCK", "An object that tells the time"),
    ("SPOON", "Use this utensil to eat soup"),
    ("CHAIR", "A seat with a back"),
    ("CROWN", "A monarch wears this"),
    ("HORSE", "An animal ridden with a saddle"),
    ("SNAIL", "A slow creature with a shell"),
    ("TRAIN", "A vehicle running on rails"),
    ("SUGAR", "Sweet crystals for your tea"),
    ("BROOM", "A tool for sweeping floors"),
    ("FROST", "A thin coating of ice"),
];
