use crate::ui::UiAction;

pub(super) fn requires_new_confirmation(action: UiAction) -> bool {
    matches!(
        action,
        UiAction::Game2048Size(_)
            | UiAction::CycleGameVariant
            | UiAction::SolitaireNew
            | UiAction::MineRestart
            | UiAction::MinePreset(_)
            | UiAction::SudokuDifficulty(_)
            | UiAction::NonogramPreset(_)
            | UiAction::FreeCellNew
            | UiAction::FivefoldNew
            | UiAction::ReversiNew
            | UiAction::LightsOutNew
            | UiAction::LightsOutDifficulty(_)
            | UiAction::TicTacToeNew
            | UiAction::MemoryPairsNew
            | UiAction::SlidingPuzzleNew
            | UiAction::MastermindNew
            | UiAction::SpiderNew
            | UiAction::WordSearchNew
            | UiAction::HangmanNew
            | UiAction::HangmanCategory(_)
            | UiAction::HangmanRule(_)
            | UiAction::ConnectFourNew
            | UiAction::CheckersNew
            | UiAction::PegSolitaireNew
            | UiAction::MahjongSolitaireNew
            | UiAction::SnakeNew
            | UiAction::SnakeMode(_)
            | UiAction::BreakoutNew
            | UiAction::HigherLowerNew
            | UiAction::HigherLowerRule(_)
            | UiAction::KlondikeGolfNew
            | UiAction::BlackjackNew
            | UiAction::SpiderSolitaireNew
            | UiAction::PyramidNew
            | UiAction::PyramidDrawRule(_)
            | UiAction::TriPeaksNew
            | UiAction::TriPeaksRule(_)
            | UiAction::NimNew
            | UiAction::NimRule(_)
            | UiAction::DungeonNew
            | UiAction::DungeonDifficulty(_)
            | UiAction::PotionNew
            | UiAction::PotionDifficulty(_)
            | UiAction::TowerNew
            | UiAction::RogueNew
            | UiAction::RogueClass(_)
            | UiAction::DailyNew
            | UiAction::DotsNew
            | UiAction::DotsDifficulty(_)
            | UiAction::SokobanRestart
            | UiAction::SokobanNew
            | UiAction::MancalaNew
            | UiAction::MancalaVariant(_)
            | UiAction::HanoiNew
            | UiAction::HanoiDisks(_)
            | UiAction::NumberMatchNew
            | UiAction::NumberMatchRule(_)
            | UiAction::FloodNew
            | UiAction::FloodDifficulty(_)
            | UiAction::ColorSortNew
            | UiAction::ColorSortDifficulty(_)
            | UiAction::BattleshipNew
            | UiAction::WordGridNew
            | UiAction::WordGridMode(_)
            | UiAction::PipeNew
            | UiAction::PipePattern(_)
            | UiAction::MazeNew
            | UiAction::MazeMode(_)
            | UiAction::MatchThreeNew
            | UiAction::MatchThreeDifficulty(_)
            | UiAction::WordLadderNew
            | UiAction::WordLadderMode(_)
    )
}
