//! The single source of truth for cabinet metadata.

use crate::state::GameId;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GameCategory {
    Cards,
    Logic,
    Board,
    Word,
    Arcade,
    Misc,
}

impl GameCategory {
    pub const fn filter(self) -> u8 {
        match self {
            Self::Cards => 3,
            Self::Logic => 4,
            Self::Board => 5,
            Self::Word => 6,
            Self::Arcade => 7,
            Self::Misc => 8,
        }
    }

    pub const fn label(self) -> &'static str {
        match self {
            Self::Cards => "Cards",
            Self::Logic => "Logic",
            Self::Board => "Board",
            Self::Word => "Word",
            Self::Arcade => "Arcade",
            Self::Misc => "Misc",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompletionStrategy {
    Record,
    RuntimeOnly,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GameDescriptor {
    pub id: GameId,
    pub index: usize,
    pub title: &'static str,
    pub subtitle: &'static str,
    pub save_key: &'static str,
    pub category: GameCategory,
    pub active: bool,
    pub completion: CompletionStrategy,
    pub has_variants: bool,
}

const fn entry(
    id: GameId,
    index: usize,
    title: &'static str,
    subtitle: &'static str,
    save_key: &'static str,
    category: GameCategory,
    has_variants: bool,
) -> GameDescriptor {
    GameDescriptor {
        id,
        index,
        title,
        subtitle,
        save_key,
        category,
        active: true,
        completion: CompletionStrategy::Record,
        has_variants,
    }
}

const fn runtime_entry(
    id: GameId,
    index: usize,
    title: &'static str,
    subtitle: &'static str,
    save_key: &'static str,
    category: GameCategory,
    has_variants: bool,
) -> GameDescriptor {
    GameDescriptor {
        id,
        index,
        title,
        subtitle,
        save_key,
        category,
        active: true,
        completion: CompletionStrategy::RuntimeOnly,
        has_variants,
    }
}

pub const ALL: [GameDescriptor; 47] = [
    entry(
        GameId::Solitaire,
        0,
        "Solitaire",
        "Classic card table",
        "solitaire",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::FreeCell,
        1,
        "FreeCell",
        "Four open cells",
        "freecell",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::Sudoku,
        2,
        "Sudoku",
        "Numbers in every nook",
        "sudoku",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::Minesweeper,
        3,
        "Minesweeper",
        "Read the field",
        "minesweeper",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::Game2048,
        4,
        "2048",
        "Slide the cabinet tiles",
        "2048",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::Nonogram,
        5,
        "Nonogram",
        "Paint the hidden picture",
        "nonogram",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::Yahtzee,
        6,
        "Fivefold",
        "Five dice, thirteen calls",
        "fivefold",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::Reversi,
        7,
        "Reversi",
        "Turn the board",
        "reversi",
        GameCategory::Board,
        true,
    ),
    entry(
        GameId::LightsOut,
        8,
        "Lights Out",
        "Settle the lights",
        "lights_out",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::TicTacToe,
        9,
        "Tic-Tac-Toe",
        "Three in a row",
        "tic_tac_toe",
        GameCategory::Board,
        true,
    ),
    entry(
        GameId::MemoryPairs,
        10,
        "Memory",
        "Find the pairs",
        "memory_pairs",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::SlidingPuzzle,
        11,
        "Sliding Puzzle",
        "Move the tiles",
        "sliding_puzzle",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::Mastermind,
        12,
        "Mastermind",
        "Read the color code",
        "mastermind",
        GameCategory::Word,
        true,
    ),
    entry(
        GameId::Spider,
        13,
        "Spider",
        "Build the webs",
        "spider",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::WordSearch,
        14,
        "Word Search",
        "Find the hidden words",
        "word_search",
        GameCategory::Word,
        true,
    ),
    entry(
        GameId::Hangman,
        15,
        "Hangman",
        "Keep the word",
        "hangman",
        GameCategory::Word,
        true,
    ),
    entry(
        GameId::ConnectFour,
        16,
        "Connect Four",
        "Drop the discs",
        "connect_four",
        GameCategory::Board,
        true,
    ),
    entry(
        GameId::Checkers,
        17,
        "Checkers",
        "Turn the pieces",
        "checkers",
        GameCategory::Board,
        true,
    ),
    entry(
        GameId::PegSolitaire,
        18,
        "Peg Solitaire",
        "Leave one peg",
        "peg_solitaire",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::MahjongSolitaire,
        19,
        "Mahjong Solitaire",
        "Pair the tiles",
        "mahjong_solitaire",
        GameCategory::Cards,
        true,
    ),
    runtime_entry(
        GameId::Snake,
        20,
        "Snake",
        "Guide the coil",
        "snake",
        GameCategory::Arcade,
        true,
    ),
    runtime_entry(
        GameId::Breakout,
        21,
        "Breakout",
        "Bounce the ball",
        "breakout",
        GameCategory::Arcade,
        true,
    ),
    entry(
        GameId::HigherLower,
        22,
        "Higher or Lower",
        "Read the card",
        "higher_lower",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::KlondikeGolf,
        23,
        "Klondike Golf",
        "Clear the columns",
        "klondike_golf",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::Blackjack,
        24,
        "Blackjack",
        "Hold the hand",
        "blackjack",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::SpiderSolitaire,
        25,
        "Spider Solitaire",
        "Build suited webs",
        "spider_solitaire",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::DungeonSweeper,
        26,
        "Dungeon Sweeper",
        "Recover relics and escape",
        "dungeon_sweeper",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::Potion2048,
        27,
        "Potion 2048",
        "Brew the next tile",
        "potion_2048",
        GameCategory::Misc,
        true,
    ),
    runtime_entry(
        GameId::TinyTowerDefence,
        28,
        "Tiny Tower Defence",
        "Keep the lanes",
        "tiny_tower_defence",
        GameCategory::Arcade,
        true,
    ),
    entry(
        GameId::OneRoomRoguelike,
        29,
        "One Room Roguelike",
        "Survive five rooms",
        "one_room_roguelike",
        GameCategory::Misc,
        true,
    ),
    entry(
        GameId::DailyDungeon,
        30,
        "Daily Dungeon",
        "Recover the daily runes",
        "daily_dungeon",
        GameCategory::Board,
        true,
    ),
    entry(
        GameId::DotsBoxes,
        31,
        "Dots & Boxes",
        "Draw the squares",
        "dots_boxes",
        GameCategory::Misc,
        true,
    ),
    entry(
        GameId::Sokoban,
        32,
        "Sokoban",
        "Push the crates",
        "sokoban",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::Mancala,
        33,
        "Mancala",
        "Sow the stones",
        "mancala",
        GameCategory::Board,
        true,
    ),
    entry(
        GameId::Hanoi,
        34,
        "Hanoi",
        "Move the disks",
        "hanoi",
        GameCategory::Board,
        true,
    ),
    entry(
        GameId::NumberMatch,
        35,
        "Number Match",
        "Pair the numbers",
        "number_match",
        GameCategory::Word,
        true,
    ),
    entry(
        GameId::FloodIt,
        36,
        "Flood It",
        "Fill the field",
        "flood_it",
        GameCategory::Misc,
        true,
    ),
    entry(
        GameId::ColorSort,
        37,
        "Color Sort",
        "Sort the colors",
        "color_sort",
        GameCategory::Misc,
        true,
    ),
    entry(
        GameId::Battleship,
        38,
        "Battleship",
        "Find the fleet",
        "battleship",
        GameCategory::Board,
        true,
    ),
    entry(
        GameId::WordGrid,
        39,
        "Word Grid",
        "Solve the word",
        "word_grid",
        GameCategory::Word,
        true,
    ),
    entry(
        GameId::PipeLoop,
        40,
        "Pipe Loop",
        "Join the pipes",
        "pipe_loop",
        GameCategory::Logic,
        true,
    ),
    entry(
        GameId::MazeWalk,
        41,
        "Maze Walk",
        "Find the exit",
        "maze_walk",
        GameCategory::Word,
        true,
    ),
    entry(
        GameId::MatchThree,
        42,
        "Match Three",
        "Clear the colors",
        "match_three",
        GameCategory::Misc,
        true,
    ),
    entry(
        GameId::Pyramid,
        43,
        "Pyramid",
        "Pair the thirteen",
        "pyramid",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::TriPeaks,
        44,
        "TriPeaks",
        "Clear the three peaks",
        "tri_peaks",
        GameCategory::Cards,
        true,
    ),
    entry(
        GameId::Nim,
        45,
        "Nim",
        "Take the stones",
        "nim",
        GameCategory::Board,
        true,
    ),
    entry(
        GameId::WordLadder,
        46,
        "Word Ladder",
        "Climb the words",
        "word_ladder",
        GameCategory::Word,
        true,
    ),
];

pub fn descriptor(game: GameId) -> &'static GameDescriptor {
    let index = GameId::ALL
        .iter()
        .position(|candidate| *candidate == game)
        .expect("every GameId must be registered");
    &ALL[index]
}

#[cfg(test)]
mod tests;
