use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GameId {
    Solitaire,
    FreeCell,
    Sudoku,
    Minesweeper,
    Game2048,
    Nonogram,
    Yahtzee,
    Reversi,
    LightsOut,
    TicTacToe,
    MemoryPairs,
    SlidingPuzzle,
    Mastermind,
    Spider,
    WordSearch,
    Hangman,
    ConnectFour,
    Checkers,
    PegSolitaire,
    MahjongSolitaire,
    Snake,
    Breakout,
    HigherLower,
    KlondikeGolf,
    Blackjack,
    SpiderSolitaire,
    DungeonSweeper,
    Potion2048,
    TinyTowerDefence,
    OneRoomRoguelike,
    DailyDungeon,
    DotsBoxes,
    Sokoban,
    Mancala,
    Hanoi,
    NumberMatch,
    FloodIt,
    ColorSort,
    Battleship,
    WordGrid,
    PipeLoop,
    MazeWalk,
    MatchThree,
    Pyramid,
    TriPeaks,
    Nim,
    WordLadder,
    SpaceInvaders,
    Asteroids,
    Frogger,
    MunchMaze,
    BlockStack,
    TerrainCannon,
    FlingFury,
    PaddleDuel,
    RiddleRoom,
    PatternVault,
    SumCircuit,
    OrbitOrder,
    WordForge,
}
impl GameId {
    pub const ALL: [Self; 60] = [
        Self::Solitaire,
        Self::FreeCell,
        Self::Sudoku,
        Self::Minesweeper,
        Self::Game2048,
        Self::Nonogram,
        Self::Yahtzee,
        Self::Reversi,
        Self::LightsOut,
        Self::TicTacToe,
        Self::MemoryPairs,
        Self::SlidingPuzzle,
        Self::Mastermind,
        Self::Spider,
        Self::WordSearch,
        Self::Hangman,
        Self::ConnectFour,
        Self::Checkers,
        Self::PegSolitaire,
        Self::MahjongSolitaire,
        Self::Snake,
        Self::Breakout,
        Self::HigherLower,
        Self::KlondikeGolf,
        Self::Blackjack,
        Self::SpiderSolitaire,
        Self::DungeonSweeper,
        Self::Potion2048,
        Self::TinyTowerDefence,
        Self::OneRoomRoguelike,
        Self::DailyDungeon,
        Self::DotsBoxes,
        Self::Sokoban,
        Self::Mancala,
        Self::Hanoi,
        Self::NumberMatch,
        Self::FloodIt,
        Self::ColorSort,
        Self::Battleship,
        Self::WordGrid,
        Self::PipeLoop,
        Self::MazeWalk,
        Self::MatchThree,
        Self::Pyramid,
        Self::TriPeaks,
        Self::Nim,
        Self::WordLadder,
        Self::SpaceInvaders,
        Self::Asteroids,
        Self::Frogger,
        Self::MunchMaze,
        Self::BlockStack,
        Self::TerrainCannon,
        Self::FlingFury,
        Self::PaddleDuel,
        Self::RiddleRoom,
        Self::PatternVault,
        Self::SumCircuit,
        Self::OrbitOrder,
        Self::WordForge,
    ];
    pub fn descriptor(self) -> &'static crate::game_descriptor::GameDescriptor {
        crate::game_descriptor::descriptor(self)
    }

    /// Stable content key used by the embedded authored-data catalog.
    pub const fn key(self) -> &'static str {
        match self {
            Self::Solitaire => "solitaire",
            Self::FreeCell => "free_cell",
            Self::Sudoku => "sudoku",
            Self::Minesweeper => "minesweeper",
            Self::Game2048 => "game_2048",
            Self::Nonogram => "nonogram",
            Self::Yahtzee => "yahtzee",
            Self::Reversi => "reversi",
            Self::LightsOut => "lights_out",
            Self::TicTacToe => "tic_tac_toe",
            Self::MemoryPairs => "memory_pairs",
            Self::SlidingPuzzle => "sliding_puzzle",
            Self::Mastermind => "mastermind",
            Self::Spider => "spider",
            Self::WordSearch => "word_search",
            Self::Hangman => "hangman",
            Self::ConnectFour => "connect_four",
            Self::Checkers => "checkers",
            Self::PegSolitaire => "peg_solitaire",
            Self::MahjongSolitaire => "mahjong_solitaire",
            Self::Snake => "snake",
            Self::Breakout => "breakout",
            Self::HigherLower => "higher_lower",
            Self::KlondikeGolf => "klondike_golf",
            Self::Blackjack => "blackjack",
            Self::SpiderSolitaire => "spider_solitaire",
            Self::DungeonSweeper => "dungeon_sweeper",
            Self::Potion2048 => "potion_2048",
            Self::TinyTowerDefence => "tiny_tower_defence",
            Self::OneRoomRoguelike => "one_room_roguelike",
            Self::DailyDungeon => "daily_dungeon",
            Self::DotsBoxes => "dots_boxes",
            Self::Sokoban => "sokoban",
            Self::Mancala => "mancala",
            Self::Hanoi => "hanoi",
            Self::NumberMatch => "number_match",
            Self::FloodIt => "flood_it",
            Self::ColorSort => "color_sort",
            Self::Battleship => "battleship",
            Self::WordGrid => "word_grid",
            Self::PipeLoop => "pipe_loop",
            Self::MazeWalk => "maze_walk",
            Self::MatchThree => "match_three",
            Self::Pyramid => "pyramid",
            Self::TriPeaks => "tri_peaks",
            Self::Nim => "nim",
            Self::WordLadder => "word_ladder",
            Self::SpaceInvaders => "space_invaders",
            Self::Asteroids => "asteroids",
            Self::Frogger => "frogger",
            Self::MunchMaze => "munch_maze",
            Self::BlockStack => "block_stack",
            Self::TerrainCannon => "terrain_cannon",
            Self::FlingFury => "fling_fury",
            Self::PaddleDuel => "paddle_duel",
            Self::RiddleRoom => "riddle_room",
            Self::PatternVault => "pattern_vault",
            Self::SumCircuit => "sum_circuit",
            Self::OrbitOrder => "orbit_order",
            Self::WordForge => "word_forge",
        }
    }
    pub fn title(self) -> &'static str {
        self.descriptor().title
    }
    pub fn subtitle(self) -> &'static str {
        self.descriptor().subtitle
    }
    pub fn index(self) -> usize {
        self.descriptor().index
    }
    pub fn save_key(self) -> &'static str {
        self.descriptor().save_key
    }
}
